export const HOME_LOAD_QUESTIONS_BEGIN = 'HOME_LOAD_QUESTIONS_BEGIN';
export const HOME_LOAD_QUESTIONS_SUCCESS = 'HOME_LOAD_QUESTIONS_SUCCESS';
export const HOME_LOAD_QUESTIONS_FAILURE = 'HOME_LOAD_QUESTIONS_FAILURE';
export const HOME_LOAD_QUESTIONS_DISMISS_ERROR = 'HOME_LOAD_QUESTIONS_DISMISS_ERROR';
export const HOME_NEXT_PAGE = 'HOME_NEXT_PAGE';
